#!/usr/bin/env bun
/**
 * One home per identifier, enforced (AGENTS.md § G, "One home per identifier").
 *
 * A literal becomes a constant when it is an IDENTIFIER — something elsewhere must spell the same
 * way. It stays inline when it is a LEAF: renaming it breaks nothing but its own appearance. The
 * test is "if I rename this, does anything else break?", and everything this check guards answers
 * yes: a role compared in a guard and stored in a column, a status written into a partial index, a
 * Redis namespace a writer and a reader have to agree on, a queue name a producer and a worker have
 * to agree on.
 *
 * What makes those worth a build failure rather than a review comment is that none of them fail
 * loudly when they disagree. A misspelled queue name still enqueues. A misspelled Redis prefix
 * still writes. The writer and the reader both look healthy and simply never meet.
 *
 * The words themselves are READ OUT OF EACH HOME, never listed in the config. A version that
 * listed them in the config has the exact defect it exists to prevent: rename a word in the home
 * and the config goes on naming the old one, so the gate polices a value nothing uses and lets a
 * freshly typed copy of the NEW word straight through. A check that enforces one home must have
 * one itself. The config says only WHICH files are homes and WHO is excused.
 *
 * TESTS ARE IN SCOPE, with one reasoned exception: a test whose whole purpose is to prove two
 * sides agree must keep its own literal, because a contract test that imports the constant it is
 * checking against proves only that the constant equals itself. Those live in `allow` with exactly
 * that reason.
 *
 * Config: `scripts/check/constants.config.json`, an array with one entry per vocabulary:
 *
 *   [{ "name": "roles", "home": "src/lib/constants/roles.ts",
 *      "allow": [{ "path": "src/lib/<area>/<file>.ts", "reason": "<why this spelling is not ours>" }] }]
 *
 * `allow` paths are prefixes; every entry needs a reason and must still excuse something.
 */

import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');
const SRC_DIR = join(ROOT, 'src');
const CONFIG_PATH = join(ROOT, 'scripts', 'check', 'constants.config.json');

/* Frozen: a migration is a record of what was applied, and rewriting one to reference a constant
   would be rewriting history a production database has already run.

   `src/db/schema/auth.ts` is generated by the auth library's CLI, so an edit there is not durable;
   it is skipped rather than allowed, because an `allow` entry would have to claim a literal the
   generator may stop writing. */
const SKIPPED = ['src/db/migrations/', 'src/db/schema/auth.ts'];

interface AllowEntry {
  path: string;
  reason: string;
}

interface Family {
  name: string;
  home: string;
  allow: AllowEntry[];
}

const failures: string[] = [];

function fail(check: string, detail: string): void {
  failures.push(`${check}: ${detail}`);
}

function collectFiles(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) collectFiles(full, out);
    else if (full.endsWith('.ts')) out.push(full);
  }
  return out;
}

/* Comment characters are blanked rather than removed, so reported line numbers stay correct. The
   line-comment pattern needs whitespace before `//`, leaving `https://…` inside a string alone.

   Every home carries prose explaining WHY the vocabulary is what it is — why a privileged subset
   exists, why a status is plain text and not a database enum — and that prose names the values. A
   check that failed the build for naming a role in a sentence would be obeyed by deleting the
   sentence, which is the opposite of the point. */
const blank = (match: string): string => match.replace(/[^\n]/g, ' ');

/* OpenAPI `summary` and `description` values are documentation that happens to live in a string
   rather than in a comment, and the same argument applies to them: a route may explain which role
   a new account starts with. Neither field is ever read to build a key or compared to a status. */
function withoutProse(source: string): string {
  return source.replace(/\b(?:description|summary)\s*:\s*(['"`])(?:\\.|(?!\1)[\s\S])*?\1/g, blank);
}

/* Strings come FIRST in this alternation, and that ordering is the whole point. A naive
   `/\/\*[\s\S]*?\*\//` blanker treats the `'/*'` in Hono's `app.use('/*', requireRole(...))` as a
   comment opener and blanks everything up to the next comment closer, which swallows the very
   role argument this check exists to find and reports the file clean.

   Matching strings and templates as tokens in the same pass means a comment opener inside a string
   is consumed as part of the string and never read as a comment. */
const CODE_TOKEN =
  /(['"])(?:\\.|(?!\1)[^\\\n])*\1|`(?:\\.|[^\\`])*`|\/\*[\s\S]*?\*\/|(?<=^|\s)\/\/[^\n]*/g;

function withoutComments(source: string): string {
  return withoutProse(source).replace(CODE_TOKEN, (match) =>
    match.startsWith('/*') || match.startsWith('//') ? blank(match) : match,
  );
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const STRING_LITERAL = /(['"])((?:\\.|(?!\1)[^\\\n])*)\1/g;

/**
 * The vocabulary a home declares, read out of the home.
 *
 * Every string literal that initialises a top-level SCREAMING_SNAKE `const` — whether the
 * initialiser is the string itself (`const EMAIL_QUEUE = 'email'`), an object of them
 * (`const ROLE = { admin: 'admin' } as const`), or an array of them. Nothing else in a home is a
 * vocabulary word: a `typeof x === 'string'` inside a type predicate is not a declaration, which is
 * why function bodies are never read.
 *
 * Narrow on purpose. A looser sweep would pick up `'string'` from the predicates homes carry and
 * then flag every `typeof` check in the codebase, which is how a check earns its way onto the list
 * of things people skip.
 */
function literalsDeclaredIn(source: string): string[] {
  const found: string[] = [];
  const declaration = /^(?:export\s+)?const\s+[A-Z][A-Z0-9_]*\b/gm;

  for (const match of source.matchAll(declaration)) {
    const assign = source.indexOf('=', match.index + match[0].length);
    if (assign === -1) continue;

    /* Walk to the `;` that closes THIS declaration, so an object or array initialiser is read
       whole and the next declaration is never swallowed. */
    let depth = 0;
    let end = assign + 1;
    for (; end < source.length; end += 1) {
      const char = source[end];
      if (char === '{' || char === '[' || char === '(') depth += 1;
      else if (char === '}' || char === ']' || char === ')') depth -= 1;
      else if (char === ';' && depth === 0) break;
    }

    for (const literal of source.slice(assign, end).matchAll(STRING_LITERAL)) {
      if (literal[2]) found.push(literal[2]);
    }
  }

  return [...new Set(found)];
}

/**
 * Where a vocabulary word counts as SPELLED.
 *
 * Two shapes of literal, told apart by their last character, because they are used differently:
 *
 *   A **prefix** ends in a delimiter — `session:`, `email:welcome:`. It is self-delimiting, so it
 *   matches at the HEAD of any string: `'session:'`, `` `session:${userId}` `` and the
 *   hand-assembled `'email:welcome:user-1'` are all the same mistake, and the last of those is the
 *   one a key builder exists to prevent.
 *
 *   A **whole value** does not — `admin`, `paid`, `email`. It matches only a complete string.
 *   Anything looser is unusable: `'member@example.com'` is a fixture address, `'not-a-member'` is
 *   an error discriminant, and a check that flagged either would be switched off within a week.
 *
 * Template literals are read the same way as quoted strings, so `` `session:${id}` `` is caught
 * and `` `${SESSION_PREFIX}${id}` `` is not.
 */
function patternFor(literal: string): RegExp {
  const value = escapeRegExp(literal);
  const isPrefix = /[^A-Za-z0-9]$/.test(literal);
  /* A prefix may be followed by the rest of the key; a whole value must run to the closing quote,
     or be the entire head of a template literal. */
  const body = isPrefix ? `${value}[^'"\\n]*` : value;
  return new RegExp(`(?:(['"])${body}\\1|\`${value}(?:\`|\\$\\{))`, 'g');
}

function lineOf(source: string, index: number): number {
  return source.slice(0, index).split('\n').length;
}

/** Every place this source spells one of the family's words, with the line it is on. */
function spellingsIn(source: string, literals: string[]): Array<{ literal: string; line: number }> {
  const hits: Array<{ literal: string; line: number }> = [];

  for (const literal of literals) {
    for (const match of source.matchAll(patternFor(literal))) {
      hits.push({ literal, line: lineOf(source, match.index) });
    }
  }

  return hits;
}

/* A config entry that is not the documented shape fails here, by name, rather than as a stack
   trace from the first property read. */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isAllowEntry(value: unknown): value is AllowEntry {
  return isRecord(value) && typeof value.path === 'string' && typeof value.reason === 'string';
}

function isFamily(value: unknown): value is Family {
  return (
    isRecord(value) &&
    typeof value.name === 'string' &&
    typeof value.home === 'string' &&
    Array.isArray(value.allow) &&
    value.allow.every(isAllowEntry)
  );
}

/* ── Config ─────────────────────────────────────────────────────────────────── */
const parsed: unknown = JSON.parse(readFileSync(CONFIG_PATH, 'utf8'));
if (!Array.isArray(parsed) || !parsed.every(isFamily)) {
  console.error(
    '\nConstant homes: scripts/check/constants.config.json must be an array of ' +
      '{ name, home, allow: [{ path, reason }] } — see the header of scripts/check/constants.ts.\n',
  );
  process.exit(1);
}

/* An empty list is the check with nothing to enforce, and a gate that passes on nothing reads as a
   clean repo. Every backend has at least one shared vocabulary (roles, queue names, cache
   prefixes): name its home, or take this gate out of scripts/check/gates.list and the quality gate
   deliberately and mark the rule Not met in AGENTS.md's Compliance Status. */
if (parsed.length === 0) {
  console.error(
    '\nConstant homes: scripts/check/constants.config.json lists no home, so nothing was checked.\n' +
      'Add one entry per shared vocabulary (see the header of scripts/check/constants.ts).\n',
  );
  process.exit(1);
}

const families: Family[] = parsed;
const sourceFiles = collectFiles(SRC_DIR);
const derived = new Map<string, string[]>();

for (const family of families) {
  const homeRel = family.home;
  if (!existsSync(join(ROOT, homeRel))) {
    fail('missing home', `${family.name}: ${homeRel} does not exist`);
    continue;
  }
  const homeSource = withoutComments(readFileSync(join(ROOT, homeRel), 'utf8'));
  const literals = literalsDeclaredIn(homeSource);
  derived.set(family.name, literals);

  /* Zero is never "nothing to check" — a home with no vocabulary would not be a home. It means the
     declarations moved into a shape this cannot read, and a check that silently scanned for nothing
     would report a clean pass over an unguarded codebase. */
  if (literals.length === 0) {
    fail('no vocabulary', `${family.name}: no declared string literals found in ${homeRel}`);
    continue;
  }

  /* Counted per entry, so an exemption that suppresses nothing can be reported as stale. */
  const suppressed = new Map<string, number>(family.allow.map((entry) => [entry.path, 0]));

  for (const entry of family.allow) {
    if (!entry.reason.trim()) {
      fail('unjustified exemption', `${family.name}: ${entry.path} is allowed with no reason`);
    }
  }

  for (const file of sourceFiles) {
    const rel = relative(ROOT, file);
    if (rel === homeRel) continue;
    if (SKIPPED.some((skipped) => rel.startsWith(skipped))) continue;

    const allowed = family.allow.find((entry) => rel.startsWith(entry.path));
    const hits = spellingsIn(withoutComments(readFileSync(file, 'utf8')), literals);

    if (allowed) {
      suppressed.set(allowed.path, (suppressed.get(allowed.path) ?? 0) + hits.length);
      continue;
    }

    for (const hit of hits) {
      fail('raw literal', `${rel}:${hit.line} — '${hit.literal}' must come from ${homeRel}`);
    }
  }

  /* A reason with nothing left to excuse is an unreviewed exemption: the code it was written about
     has changed, and nobody re-asked whether it still applies. Removing it is the whole maintenance
     burden, and leaving it is how an allowlist silently grows a hole. */
  for (const entry of family.allow) {
    if ((suppressed.get(entry.path) ?? 0) === 0) {
      fail(
        'stale exemption',
        `${family.name}: ${entry.path} is allowed for "${entry.reason}" but spells none of its literals`,
      );
    }
  }
}

/* ── Report ─────────────────────────────────────────────────────────────────── */
/* The derived vocabulary is printed on a pass as well as a failure. What this check scans is not
   written down anywhere a reader can open, so the run has to say it — a silent pass over a home
   whose declarations stopped parsing would otherwise look identical to a real one. */
function describeFamilies(): string {
  return families
    .map((family) => {
      const literals = derived.get(family.name) ?? [];
      const words = literals.map((literal) => `'${literal}'`).join(', ') || '(none)';
      return `  ${family.name} — ${family.home}\n    ${words}`;
    })
    .join('\n');
}

if (failures.length > 0) {
  console.error(`\nConstant homes: ${failures.length} problem(s)\n`);
  for (const failure of failures) console.error(`  ✗ ${failure}`);
  console.error('\nVocabulary read from each home:');
  console.error(describeFamilies());
  console.error('\nSee scripts/check/constants.config.json for the homes and their exemptions.\n');
  process.exit(1);
}

const total = [...derived.values()].reduce((sum, literals) => sum + literals.length, 0);
console.log(
  `Constant homes: ${families.length} families, ${total} identifiers, ` +
    `${sourceFiles.length} source file(s) scanned, all checks passed`,
);
console.log(describeFamilies());
